name: taskmaster
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  provider: ^6.1.2
  logger: ^2.5.0
  sqflite: ^2.4.1
  path: ^1.9.0
  table_calendar: ^3.2.0
  workmanager: ^0.5.2
  http: ^1.6.0
  dio: ^5.0.0
  flutter_secure_storage: ^9.0.0
  timezone_dropdown: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/

founts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppings-Bold.ttf
        weight: 700
      - asset: fonts/Poppings-Medium.ttf
        weight: 500
      - asset: fonts/Poppings-Regular.ttf
        weight: 400
      - asset: fonts/Poppings-SemiBold.ttf
        weight: 600


